apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers: 
      - name: nginx
        image: vinsdocker/nginx-gke
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata: 
  name: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001