apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deploy
  namespace: default
  labels:
    app:  my-deploy
spec:
  selector:
    matchLabels:
      app: my-deploy
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  my-deploy
    spec:
      containers:
      - name:  nginx
        image:  nginx
        resources:
          requests:
            cpu: 2
            memory: 100Mi
          limits:
            cpu: 2
            memory: 100Mi