apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  mongo-db
  namespace: default
  labels:
    app:  mongo-db
spec:
  serviceName: mongo-service
  selector:
    matchLabels:
      app: mongo-db
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongo-db
    spec:
      containers:
      - name:  mongo-db
        image:  mongo:4.4-focal
        envFrom:
        - secretRef:
            name: mongo-secret
        ports:
        - containerPort:  27017
          name:  mongo-db-port
        volumeMounts:
          - name: "init-file"
            mountPath: /docker-entrypoint-initdb.d
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: "init-file"
          configMap: 
              name: mongo-init-js
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      