apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-express-app
  namespace: default
  labels:
    app:  mongo-express-app
spec:
  selector:
    matchLabels:
      app: mongo-express-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mongo-express-app
    spec:
      containers:
      - name:  mongo-express-app
        image:  mongo-express:1.0.0-alpha.4
        ports:
        - containerPort:  8081
          name:  express-port
        envFrom:
        - secretRef:
            name: express-secret
        - configMapRef:
            name: express-config
      restartPolicy: Always