apiVersion: v1
kind: Service
metadata:
  name: express-service
  namespace: default
spec:
  selector:
    app: mongo-express-app
  ports:
  - name: express-service
    protocol: TCP
    port: 8081
    targetPort: 8081