apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  minReadySeconds:  10
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec: 
      containers: 
      - name: redis
        image: redis:6
        ports:
        - name: "redis-port"
          containerPort:  6379


 