apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy-assignment
spec:
  minReadySeconds:  10
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-deploy-assignment
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-deploy-assignment
    spec: 
      containers: 
      - name: order-service
        image: vinsdocker/k8s-deploy-assignment
        ports:
        - name: "app-port"
          containerPort:  8080
        env:
        - name: spring.redis.host
          value: 10.244.1.52
        - name: spring.redis.port
          value: "6379"


