apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    managed-by: rahul
    team: team-a
spec: 
  containers: 
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    managed-by: rahul
    team: team-a
spec: 
  containers: 
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    managed-by: rahul
    team: team-a
spec: 
  containers: 
  - name: nginx
    image: nginx
