apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: request.timeout
      value: "10ms"
    - name: date
      value: "dsdsds"
    args: 
    - "env"

