kind: ConfigMap
apiVersion: v1
metadata:
  name: app-propertied
  namespace: default
data:
  name: "app-name"
  timeout: "30s"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec: 
  restartPolicy: Never
  containers: 
  - name: ubuntu
    image: ubuntu
    env:
    - name: "request.timeout"
      valueFrom:
        configMapKeyRef: 
          name: app-propertied
          key: timeout
    - name: "application.url"
      valueFrom:
        configMapKeyRef: 
          name: app-propertied
          key: "name"
    args:
    - env
