apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  username: cmFodWw=
  password: YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec: 
  restartPolicy: Never
  containers: 
  - name: ubuntu
    image: ubuntu
    envFrom:
    - secretRef:
        name: app-secret 
    args:
    - env