kind: Secret
apiVersion: v1
metadata:
  name: app-secret
  namespace: default
data:
  app.key: |
    a2luZDogQ29uZmlnTWFwCmFwaVZlcnNpb246IHYxCm1ldGFkYXRhOgogIG5hbWU6IGFwcC1wcm9w
    ZXJ0aWVkCiAgbmFtZXNwYWNlOiBkZWZhdWx0CmRhdGE6CiAgbmFtZTogImFwcC1uYW1lIgogIHRp
    bWVvdXQ6ICIzMHMi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec: 
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers: 
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: secret-volume
      mountPath: "/usr/share/props"
    args:
      - "sleep"
      - "3600"
  volumes:
  - name: secret-volume
    secret:  
      secretName: app-secret