apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  namespace: default
  labels:
    app: my-pv
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  