apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pod-volumes
      mountPath: /usr/share/nginx/html
  volumes:
    - name: pod-volumes
      persistentVolumeClaim:
        claimName: my-pv