apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv
  namespace: default
  labels:
    app: my-pv
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers: 
      - name: nginx
        image: nginx
        startupProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - 'echo "$(hostname) </br>" >> /usr/share/nginx/html/index.html'
        volumeMounts:
        - name: pod-volumes
          mountPath: /usr/share/nginx/html
      volumes:
        - name: pod-volumes
          persistentVolumeClaim:
            claimName: my-pv

