
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      containers: 
      - name: nginx
        image: nginx
        startupProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - 'echo "$(hostname) </br>" >> /usr/share/nginx/html/index.html'
        volumeMounts:
        - name: my-pv
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: my-pv
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
