apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec: 
  containers: 
  - name: mongo
    image: mongo
    startupProbe:
      tcpSocket:
        port: 27017
      periodSeconds: 1
      failureThreshold: 5
